version: 2.1

jobs:
  test-android:
    docker:
    - image: circleci/android:api-28
    steps:
    - checkout
    - run:
        name: test android build
        command: ./gradlew -PlastFMApiKey=fake-token
    - store_test_results:
        path: "app/build/test-results/testDebugUnitTest/"

workflows:
  version: 2.0
  android:
    jobs:
      - test-android